name: Build ARM64

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          zlib1g-dev \
          liblzo2-dev \
          libssl-dev \
          unicode \
          clang \
          llvm \
          lld \
          lldb
    
    - name: Clean previous builds
      run: make clean
    
    - name: Build for ARM64
      run: |
        make --jobs $(nproc)
    
    - name: Verify ARM64 binary
      run: |
        echo "Checking for built binaries..."
        if [ -f bin/quickbms64 ]; then
          echo "Found bin/quickbms64:"
          file bin/quickbms64
          ls -la bin/quickbms64
        elif [ -f bin/quickbms ]; then
          echo "Found bin/quickbms:"
          file bin/quickbms
          ls -la bin/quickbms
        else
          echo "Binary not found in expected location"
          echo "Contents of bin/ directory:"
          ls -la bin/ 2>/dev/null || echo "bin/ directory not found"
          echo "Searching for quickbms binaries:"
          find . -name "quickbms*" -type f -executable 2>/dev/null || echo "No quickbms executables found"
        fi
    
    - name: Create release artifacts
      run: |
        mkdir -p artifacts/arm64
        
        # Copy the built binary
        if [ -f bin/quickbms64 ]; then
          cp bin/quickbms64 artifacts/arm64/quickbms64-arm64
          echo "Copied bin/quickbms64 to artifacts"
        elif [ -f bin/quickbms ]; then
          cp bin/quickbms artifacts/arm64/quickbms-arm64
          echo "Copied bin/quickbms to artifacts"
        else
          echo "ERROR: No binary found to copy"
          exit 1
        fi
        
        # Verify the copied binary
        echo "Final artifact verification:"
        ls -la artifacts/arm64/
        file artifacts/arm64/quickbms*-arm64
    
    - name: Upload ARM64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quickbms-arm64
        path: artifacts/arm64/
        retention-days: 30
